name: mc-gamertime

services:
  mc-gamertime:
    container_name: mc-gamertime
    image: myapp:local
    ports:
      - 4263:4263
    env_file:
      - .env
    volumes:
      - data:/data
      - avatars:/avatars
      - blog-images:/blog-images
      - game-images:/game-images
      - rulebooks:/rulebooks
    restart: unless-stopped

volumes:
  data:
  avatars:
  blog-images:
  game-images:
  rulebooks:
